name: PluginManager
version: 1.3
author: Justix
main: net.dev.pluginmanager.PluginManager
api-version: 1.13

commands:
      pluginmanager:
        aliases:
        - pluginm
        - pmanager
        - pman